# Generated by Django 5.2.7 on 2025-11-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_teacher_name', models.CharField(blank=True, max_length=100, verbose_name='ПІБ викладача')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Про викладача')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers_images')),
                ('specialties', models.CharField(blank=True, max_length=200, verbose_name='Спеціалізація(напрямок)')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
                'ordering': ['full_teacher_name'],
            },
        ),
    ]
