# Generated by Django 5.2.7 on 2025-11-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='escription',
            field=models.TextField(blank=True),
        ),
    ]
