# Generated by Django 5.2.7 on 2025-11-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs_app', '0002_actionlog_escription'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={},
        ),
        migrations.RenameField(
            model_name='actionlog',
            old_name='escription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Створення'), ('update', 'Оновлення'), ('delete', 'Видалення'), ('enroll', 'Запис на курс'), ('unenroll', 'Відпис від курсу')], max_length=20),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
