# Generated by Django 5.2.7 on 2025-10-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='courses',
            name='full_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images'),
        ),
        migrations.AddField(
            model_name='courses',
            name='short_description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
