# Generated by Django 5.2.7 on 2025-11-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='teachers',
            new_name='c_teachers',
        ),
    ]
