# Generated by Django 5.2.7 on 2025-10-13 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_remove_courses_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='current_courses',
            field=models.ManyToManyField(blank=True, related_name='current_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
