# Generated by Django 5.2.7 on 2025-10-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_courses_current_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='current_courses',
            new_name='current_users',
        ),
    ]
