# Generated by Django 5.2.7 on 2025-10-13 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_rename_current_courses_courses_current_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='current_users',
            field=models.ManyToManyField(blank=True, related_name='current_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
