# Generated by Django 5.2.7 on 2025-10-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0005_alter_courses_current_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='current_users',
        ),
    ]
