# Generated by Django 5.2.7 on 2025-10-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_remove_courses_current_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='full_description',
            new_name='program',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='short_description',
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
