# Generated by Django 5.2.7 on 2025-11-04 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_courses', models.ManyToManyField(blank=True, related_name='rn_members', to='courses_app.courses')),
                ('m_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rn_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
