# Generated by Django 5.2.7 on 2025-10-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='current_courses',
        ),
    ]
