# Generated by Django 5.2.7 on 2025-10-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_remove_courses_current_users'),
        ('members_app', '0003_rename_date_of_birth_members_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='members', to='courses_app.courses'),
        ),
    ]
